json.id note.id
json.title note.title
json.body note.body
json.bodyPlain note.body_plain
json.notebookId note.notebook_id
json.tagIds note.tag_ids
json.flagId note.flag_id
json.createdAt note.created_at
json.updatedAt note.updated_at
